'use client'
import UserProvider from '@/context/userContext'
import './globals.css'
import { Inter } from 'next/font/google'
import LoginProvider from '@/context/LoginContext'
import Header from '@/components/Header'
import ToastContainer from '@/components/ToastContainer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <LoginProvider>
            <Header />
            <ToastContainer />
            {children}
          </LoginProvider>
        </UserProvider>
      </body>
    </html>
  )
}
